// ═══════════════════════════════════════════════════════════════
// SCHEMAS — single source of truth for template field definitions.
// Both the Remotion templates and the Builder app import from here.
//
// When you add a template or modify fields:
// 1. Update the schema here
// 2. Update the Remotion template component to match
// 3. The builder auto-updates
// ═══════════════════════════════════════════════════════════════

export const SCHEMAS = [
  {
    id: "OddsCard",
    name: "T1: Odds Card",
    icon: "💰",
    desc: "Moneyline, spread, or over/under display",
    dur: 150,
    fields: [
      { k: "event", l: "Event Label", t: "text", ph: "NFL Week 1 · Sunday", d: "" },
      { k: "teamA.name", l: "Team A", t: "text", ph: "KC", d: "KC" },
      { k: "teamA.odds", l: "A Odds", t: "text", ph: "-180", d: "-180" },
      { k: "teamA.role", l: "A Role", t: "select", o: ["FAVORITE", "UNDERDOG", ""], d: "FAVORITE" },
      { k: "teamA.color", l: "A Color", t: "color", d: "#E82020" },
      { k: "teamA.logo", l: "A Logo URL", t: "text", ph: "https://...", d: "", w: { f: "useLogo", v: true } },
      { k: "teamB.name", l: "Team B", t: "text", ph: "DET", d: "DET" },
      { k: "teamB.odds", l: "B Odds", t: "text", ph: "+155", d: "+155" },
      { k: "teamB.role", l: "B Role", t: "select", o: ["FAVORITE", "UNDERDOG", ""], d: "UNDERDOG" },
      { k: "teamB.color", l: "B Color", t: "color", d: "#00c358" },
      { k: "teamB.logo", l: "B Logo URL", t: "text", ph: "https://...", d: "", w: { f: "useLogo", v: true } },
      { k: "useLogo", l: "Show Logos", t: "toggle", d: false },
      { k: "variant", l: "Variant", t: "select", o: ["two-way", "three-way"], d: "two-way" },
      { k: "draw.odds", l: "Draw Odds", t: "text", ph: "+500", d: "", w: { f: "variant", v: "three-way" } },
    ],
  },
  {
    id: "StatComparison",
    name: "T2: Stat Comparison",
    icon: "⚖️",
    desc: "Side-by-side stat bars comparing two entities",
    dur: 180,
    fields: [
      { k: "entityA.name", l: "Entity A", t: "text", d: "BOS" },
      { k: "entityA.color", l: "A Color", t: "color", d: "#FFFFFF" },
      { k: "entityA.logo", l: "A Logo URL", t: "text", ph: "https://...", d: "", w: { f: "useLogo", v: true } },
      { k: "entityB.name", l: "Entity B", t: "text", d: "MIL" },
      { k: "entityB.color", l: "B Color", t: "color", d: "#FFFFFF" },
      { k: "entityB.logo", l: "B Logo URL", t: "text", ph: "https://...", d: "", w: { f: "useLogo", v: true } },
      { k: "useLogo", l: "Show Logos", t: "toggle", d: false },
      { k: "stats", l: "Stats", t: "paste-stats", d: [{ label: "PPG", valueA: 110, valueB: 105, suffix: "" }] },
    ],
  },
  {
    id: "BigNumber",
    name: "T3: Big Number",
    icon: "🔢",
    desc: "Single dramatic stat callout with count-up",
    dur: 150,
    fields: [
      { k: "number", l: "Number", t: "text", ph: "67.5", d: "42" },
      { k: "suffix", l: "Suffix", t: "text", ph: "% or -1", d: "%" },
      { k: "label", l: "Label", t: "text", d: "Stat Label" },
      { k: "sublabel", l: "Sub-label", t: "textarea", d: "" },
      { k: "color", l: "Color", t: "color", d: "#00c358" },
      { k: "countUp", l: "Count-up", t: "toggle", d: true },
    ],
  },
  {
    id: "Timeline",
    name: "T4: Timeline",
    icon: "📈",
    desc: "Line chart showing a stat changing over time",
    dur: 210,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "yLabel", l: "Y-Axis Label", t: "text", d: "" },
      { k: "color", l: "Line Color", t: "color", d: "#00c358" },
      { k: "points", l: "Data Points", t: "paste-points", d: [{ label: "Pt 1", value: 100 }, { label: "Pt 2", value: 50 }] },
    ],
  },
  {
    id: "QuoteCard",
    name: "T5: Quote Card",
    icon: "💬",
    desc: "Quote with word-by-word reveal and attribution",
    dur: 210,
    fields: [
      { k: "quote", l: "Quote", t: "textarea", d: "" },
      { k: "attribution", l: "Attribution", t: "text", d: "" },
      { k: "role", l: "Role", t: "text", d: "" },
      { k: "variant", l: "Style", t: "select", o: ["standard", "dramatic"], d: "standard" },
    ],
  },
  {
    id: "StandingsTable",
    name: "T6: Standings Table",
    icon: "🏆",
    desc: "Rankings with highlighted rows",
    dur: 180,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "columns", l: "Columns", t: "text-list", ph: "W,L,PTS", d: ["W", "L", "PTS"] },
      { k: "rows", l: "Rows", t: "paste-table", d: [{ name: "Team 1", values: ["10", "3", "20"], highlight: true }] },
      { k: "highlightColor", l: "Highlight", t: "color", d: "#00c358" },
      { k: "useLogo", l: "Show Logos", t: "toggle", d: false },
    ],
  },
  {
    id: "Scoreboard",
    name: "T7: Scoreboard",
    icon: "🏒",
    desc: "Final score with optional badge",
    dur: 150,
    fields: [
      { k: "teamA.name", l: "Team A", t: "text", d: "USA" },
      { k: "teamA.score", l: "A Score", t: "number", d: 0 },
      { k: "teamA.logo", l: "A Logo URL", t: "text", ph: "https://...", d: "", w: { f: "useLogo", v: true } },
      { k: "teamB.name", l: "Team B", t: "text", d: "USSR" },
      { k: "teamB.score", l: "B Score", t: "number", d: 0 },
      { k: "teamB.logo", l: "B Logo URL", t: "text", ph: "https://...", d: "", w: { f: "useLogo", v: true } },
      { k: "useLogo", l: "Show Logos", t: "toggle", d: false },
      { k: "event", l: "Event", t: "text", d: "" },
      { k: "date", l: "Date", t: "text", d: "" },
      { k: "badge", l: "Badge", t: "select", o: ["", "UPSET", "FINAL", "EXHIBITION", "OT"], d: "" },
    ],
  },
  {
    id: "ProbabilityViz",
    name: "T8: Probability Viz",
    icon: "🎯",
    desc: "Donut chart or icon grid for percentages",
    dur: 180,
    fields: [
      { k: "percentage", l: "Percentage", t: "number", d: 50 },
      { k: "label", l: "Label", t: "text", d: "" },
      { k: "sublabel", l: "Sub-label", t: "text", d: "" },
      { k: "variant", l: "Style", t: "select", o: ["donut", "icon-grid"], d: "donut" },
      { k: "color", l: "Color", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "PhotoStat",
    name: "T9: Photo + Stat",
    icon: "📸",
    desc: "Stat overlay for photos/clips",
    dur: 180,
    fields: [
      { k: "headline", l: "Headline", t: "text", d: "" },
      { k: "stats", l: "Stats", t: "paste-kv", d: [{ label: "Record", value: "44-0" }] },
      { k: "photoSide", l: "Photo Side", t: "select", o: ["left", "right"], d: "left" },
      { k: "accentColor", l: "Accent", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "Explainer",
    name: "T10: Explainer Box",
    icon: "📋",
    desc: "Numbered methodology steps",
    dur: 240,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "steps", l: "Steps", t: "paste-lines", d: ["Step one", "Step two", "Step three"] },
      { k: "formula", l: "Formula / Key Insight", t: "text", d: "" },
      { k: "accentColor", l: "Accent", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "Comparable",
    name: "T11: Comparable Card",
    icon: "🔄",
    desc: "'This is like that' comparison",
    dur: 180,
    fields: [
      { k: "subjectA.name", l: "Subject A", t: "text", d: "" },
      { k: "subjectA.detail", l: "A Detail", t: "text", d: "" },
      { k: "subjectA.stat", l: "A Stat", t: "text", d: "" },
      { k: "subjectA.logo", l: "A Logo URL", t: "text", ph: "https://...", d: "", w: { f: "useLogo", v: true } },
      { k: "subjectB.name", l: "Subject B", t: "text", d: "" },
      { k: "subjectB.detail", l: "B Detail", t: "text", d: "" },
      { k: "subjectB.stat", l: "B Stat", t: "text", d: "" },
      { k: "subjectB.logo", l: "B Logo URL", t: "text", ph: "https://...", d: "", w: { f: "useLogo", v: true } },
      { k: "useLogo", l: "Show Logos", t: "toggle", d: false },
      { k: "connector", l: "Connector", t: "text", d: "IS COMPARABLE TO" },
      { k: "negated", l: "Negated (NOT)", t: "toggle", d: false },
    ],
  },
  {
    id: "LowerThird",
    name: "T12: Lower Third",
    icon: "🏷️",
    desc: "Classic broadcast lower third — speaker or source credit",
    dur: 150,
    fields: [
      { k: "primary", l: "Primary", t: "text", d: "" },
      { k: "secondary", l: "Secondary", t: "text", d: "" },
      { k: "accentColor", l: "Accent", t: "color", d: "#00c358" },
      { k: "position", l: "Position", t: "select", o: ["left", "right"], d: "left" },
    ],
  },
  {
    id: "HeatMap",
    name: "T13: Heat Map",
    icon: "🟥",
    desc: "Grid of cells with color intensity — show patterns across two axes",
    dur: 210,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "xLabels", l: "Column Labels", t: "text-list", ph: "1-3,4-6,7-9,10+", d: ["1-3", "4-6", "7-9", "10+"] },
      { k: "yLabels", l: "Row Labels", t: "text-list", ph: "1st,2nd,3rd,4th", d: ["1st", "2nd", "3rd", "4th"] },
      { k: "data", l: "Data (rows of numbers, one row per line)", t: "textarea", ph: "75,68,52,41\n71,60,48,33", d: "75,68,52,41\n71,60,48,33\n80,65,55,38\n78,62,50,35" },
      { k: "colorLow", l: "Low Color", t: "color", d: "#1E1E32" },
      { k: "colorHigh", l: "High Color", t: "color", d: "#00c358" },
      { k: "showValues", l: "Show Values", t: "toggle", d: true },
    ],
  },
  {
    id: "ScatterPlot",
    name: "T14: Scatter Plot",
    icon: "📊",
    desc: "X/Y scatter plot — find outliers and clusters",
    dur: 240,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "xLabel", l: "X-Axis Label", t: "text", d: "" },
      { k: "yLabel", l: "Y-Axis Label", t: "text", d: "" },
      { k: "points", l: "Points (label, x, y)", t: "paste-table", d: [
        { name: "KC", values: ["420", "4.9"], highlight: false },
      ]},
      { k: "quadrants.topLeft", l: "Quadrant: Top-Left", t: "text", ph: "e.g. High Y, Low X", d: "" },
      { k: "quadrants.topRight", l: "Quadrant: Top-Right", t: "text", ph: "e.g. Elite", d: "" },
      { k: "quadrants.bottomLeft", l: "Quadrant: Bottom-Left", t: "text", ph: "e.g. Eliminated", d: "" },
      { k: "quadrants.bottomRight", l: "Quadrant: Bottom-Right", t: "text", ph: "e.g. High X, Low Y", d: "" },
      { k: "useLogo", l: "Show Logos", t: "toggle", d: false },
    ],
  },
  {
    id: "FlexTable",
    name: "T15: Flex Table",
    icon: "📋",
    desc: "Flexible table — variable columns, variable rows",
    dur: 210,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "columns", l: "Column Headers", t: "paste-lines", d: ["Player", "YDS"] },
      { k: "rows", l: "Rows", t: "paste-table", d: [{ name: "Mahomes", values: ["312"], highlight: true }] },
      { k: "highlightColor", l: "Highlight Color", t: "color", d: "#00c358" },
      { k: "showRank", l: "Show Rank", t: "toggle", d: false },
      { k: "useLogo", l: "Show Logos", t: "toggle", d: false },
    ],
  },
  {
    id: "SeasonSchedule",
    name: "T16: Season Schedule",
    icon: "📅",
    desc: "Season schedule grid showing W/L results in green and red",
    dur: 240,
    fields: [
      { k: "title", l: "Title", t: "text", ph: "2024 NFL Season", d: "" },
      { k: "team", l: "Team Name", t: "text", ph: "Chiefs", d: "" },
      { k: "games", l: "Games (week, opponent, score)", t: "paste-table", d: [
        { name: "WK 1", values: ["vs Ravens", "W 27-20"], highlight: false },
        { name: "WK 2", values: ["@ Bengals", "L 17-25"], highlight: false },
      ]},
      { k: "teamLogo", l: "Team Logo URL", t: "text", ph: "https://...", d: "" },
      { k: "accentColor", l: "Team Color", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "GameFlash",
    name: "T17: Game Flash",
    icon: "⚡",
    desc: "Games flash onto screen one at a time — opponent, score, result",
    dur: 300,
    fields: [
      { k: "title", l: "Title", t: "text", ph: "2024 Season Results", d: "" },
      { k: "games", l: "Games (week, opponent, score)", t: "paste-table", d: [
        { name: "WK 1", values: ["vs Ravens", "W 27-20"], highlight: false },
        { name: "WK 2", values: ["@ Bengals", "L 17-25"], highlight: false },
      ]},
      { k: "framesPerGame", l: "Frames Per Game", t: "number", d: 30 },
      { k: "useLogo", l: "Show Logos", t: "toggle", d: false },
      { k: "accentColor", l: "Accent Color", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "ListScanner",
    name: "T18: List Scanner",
    icon: "🔍",
    desc: "Fast-scrolls through a ranked list, slows and pauses on highlighted entry",
    dur: 240,
    fields: [
      { k: "title", l: "Title", t: "text", ph: "NFL Passing Yards Leaders", d: "" },
      { k: "items", l: "Items", t: "paste-table", d: [
        { name: "Player 1", values: ["4,500 YDS"], highlight: false },
        { name: "Player 2", values: ["4,200 YDS"], highlight: true },
      ]},
      { k: "display", l: "Display Mode", t: "select", o: ["list", "dots"], d: "list" },
      { k: "showRank", l: "Show Rank", t: "toggle", d: true },
      { k: "showLabels", l: "Show Labels", t: "toggle", d: true, w: { f: "display", v: "dots" } },
      { k: "direction", l: "Scroll Direction", t: "select", o: ["down", "up"], d: "down" },
      { k: "dotColor", l: "Dot Color", t: "color", d: "#E82020", w: { f: "display", v: "dots" } },
      { k: "accentColor", l: "Accent Color", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "DotStrip",
    name: "T19: Dot Strip",
    icon: "🔴",
    desc: "Single-stat dot distribution — rows of dots climbing up or down",
    dur: 240,
    fields: [
      { k: "title", l: "Title", t: "text", ph: "Home Runs — 2024 Season", d: "" },
      { k: "items", l: "Items (name, value)", t: "paste-table", d: [
        { name: "Ohtani", values: ["54"], highlight: true },
        { name: "Judge", values: ["58"], highlight: false },
        { name: "Soto", values: ["41"], highlight: false },
      ]},
      { k: "sort", l: "Sort", t: "select", o: ["descending", "ascending", "none"], d: "descending" },
      { k: "showLabels", l: "Show Labels", t: "toggle", d: true },
      { k: "showValues", l: "Show Values", t: "toggle", d: true },
      { k: "dotColor", l: "Dot Color", t: "color", d: "#E82020" },
      { k: "accentColor", l: "Highlight Color", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "RetroTV",
    name: "T20: Retro TV",
    icon: "📺",
    desc: "CRT television frame overlay — composite highlights inside the screen",
    dur: 150,
    fields: [
      { k: "screenColor", l: "Screen Fill", t: "color", d: "#00FF00" },
      { k: "caption", l: "Caption", t: "text", ph: "4th Quarter Highlights", d: "" },
      { k: "channel", l: "Channel Label", t: "text", ph: "CH 3", d: "" },
      { k: "showStatic", l: "Power-On Static", t: "toggle", d: true },
      { k: "showScanlines", l: "Heavy Scanlines", t: "toggle", d: true },
      { k: "frameColor", l: "TV Frame Color", t: "color", d: "#1A1510" },
    ],
  },
];

for (const s of SCHEMAS) {
  s.fields.push({ k: "speed", l: "Animation Speed", t: "number", ph: "1 = normal, 0.5 = slow, 2 = fast", d: 1 });
}
