// ═══════════════════════════════════════════════════════════════
// SCHEMAS — single source of truth for template field definitions.
// Both the Remotion templates and the Builder app import from here.
//
// When you add a template or modify fields:
// 1. Update the schema here
// 2. Update the Remotion template component to match
// 3. The builder auto-updates
// ═══════════════════════════════════════════════════════════════

export const SCHEMAS = [
  {
    id: "OddsCard",
    name: "T1: Odds Card",
    icon: "💰",
    desc: "Moneyline, spread, or over/under display",
    dur: 150,
    fields: [
      { k: "event", l: "Event Label", t: "text", ph: "NFL Week 1 · Sunday", d: "" },
      { k: "teamA.name", l: "Team A", t: "text", ph: "KC", d: "KC" },
      { k: "teamA.odds", l: "A Odds", t: "text", ph: "-180", d: "-180" },
      { k: "teamA.role", l: "A Role", t: "select", o: ["FAVORITE", "UNDERDOG", ""], d: "FAVORITE" },
      { k: "teamA.color", l: "A Color", t: "color", d: "#E82020" },
      { k: "teamB.name", l: "Team B", t: "text", ph: "DET", d: "DET" },
      { k: "teamB.odds", l: "B Odds", t: "text", ph: "+155", d: "+155" },
      { k: "teamB.role", l: "B Role", t: "select", o: ["FAVORITE", "UNDERDOG", ""], d: "UNDERDOG" },
      { k: "teamB.color", l: "B Color", t: "color", d: "#00c358" },
      { k: "variant", l: "Variant", t: "select", o: ["two-way", "three-way"], d: "two-way" },
      { k: "draw.odds", l: "Draw Odds", t: "text", ph: "+500", d: "", w: { f: "variant", v: "three-way" } },
    ],
  },
  {
    id: "StatComparison",
    name: "T2: Stat Comparison",
    icon: "⚖️",
    desc: "Side-by-side stat bars comparing two entities",
    dur: 180,
    fields: [
      { k: "entityA.name", l: "Entity A", t: "text", d: "BOS" },
      { k: "entityA.color", l: "A Color", t: "color", d: "#FFFFFF" },
      { k: "entityB.name", l: "Entity B", t: "text", d: "MIL" },
      { k: "entityB.color", l: "B Color", t: "color", d: "#FFFFFF" },
      { k: "stats", l: "Stats", t: "paste-stats", d: [{ label: "PPG", valueA: 110, valueB: 105, suffix: "" }] },
    ],
  },
  {
    id: "BigNumber",
    name: "T3: Big Number",
    icon: "🔢",
    desc: "Single dramatic stat callout with count-up",
    dur: 150,
    fields: [
      { k: "number", l: "Number", t: "text", ph: "67.5", d: "42" },
      { k: "suffix", l: "Suffix", t: "text", ph: "% or -1", d: "%" },
      { k: "label", l: "Label", t: "text", d: "Stat Label" },
      { k: "sublabel", l: "Sub-label", t: "textarea", d: "" },
      { k: "color", l: "Color", t: "color", d: "#00c358" },
      { k: "countUp", l: "Count-up", t: "toggle", d: true },
    ],
  },
  {
    id: "Timeline",
    name: "T4: Timeline",
    icon: "📈",
    desc: "Line chart showing a stat changing over time",
    dur: 210,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "yLabel", l: "Y-Axis Label", t: "text", d: "" },
      { k: "color", l: "Line Color", t: "color", d: "#00c358" },
      { k: "points", l: "Data Points", t: "paste-points", d: [{ label: "Pt 1", value: 100 }, { label: "Pt 2", value: 50 }] },
    ],
  },
  {
    id: "QuoteCard",
    name: "T5: Quote Card",
    icon: "💬",
    desc: "Quote with word-by-word reveal and attribution",
    dur: 210,
    fields: [
      { k: "quote", l: "Quote", t: "textarea", d: "" },
      { k: "attribution", l: "Attribution", t: "text", d: "" },
      { k: "role", l: "Role", t: "text", d: "" },
      { k: "variant", l: "Style", t: "select", o: ["standard", "dramatic"], d: "standard" },
    ],
  },
  {
    id: "StandingsTable",
    name: "T6: Standings Table",
    icon: "🏆",
    desc: "Rankings with highlighted rows",
    dur: 180,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "columns", l: "Columns", t: "text-list", ph: "W,L,PTS", d: ["W", "L", "PTS"] },
      { k: "rows", l: "Rows", t: "paste-table", d: [{ name: "Team 1", values: ["10", "3", "20"], highlight: true }] },
      { k: "highlightColor", l: "Highlight", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "Scoreboard",
    name: "T7: Scoreboard",
    icon: "🏒",
    desc: "Final score with optional badge",
    dur: 150,
    fields: [
      { k: "teamA.name", l: "Team A", t: "text", d: "USA" },
      { k: "teamA.score", l: "A Score", t: "number", d: 0 },
      { k: "teamB.name", l: "Team B", t: "text", d: "USSR" },
      { k: "teamB.score", l: "B Score", t: "number", d: 0 },
      { k: "event", l: "Event", t: "text", d: "" },
      { k: "date", l: "Date", t: "text", d: "" },
      { k: "badge", l: "Badge", t: "select", o: ["", "UPSET", "FINAL", "EXHIBITION", "OT"], d: "" },
    ],
  },
  {
    id: "ProbabilityViz",
    name: "T8: Probability Viz",
    icon: "🎯",
    desc: "Donut chart or icon grid for percentages",
    dur: 180,
    fields: [
      { k: "percentage", l: "Percentage", t: "number", d: 50 },
      { k: "label", l: "Label", t: "text", d: "" },
      { k: "sublabel", l: "Sub-label", t: "text", d: "" },
      { k: "variant", l: "Style", t: "select", o: ["donut", "icon-grid"], d: "donut" },
      { k: "color", l: "Color", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "PhotoStat",
    name: "T9: Photo + Stat",
    icon: "📸",
    desc: "Stat overlay for photos/clips",
    dur: 180,
    fields: [
      { k: "headline", l: "Headline", t: "text", d: "" },
      { k: "stats", l: "Stats", t: "paste-kv", d: [{ label: "Record", value: "44-0" }] },
      { k: "photoSide", l: "Photo Side", t: "select", o: ["left", "right"], d: "left" },
      { k: "accentColor", l: "Accent", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "Explainer",
    name: "T10: Explainer Box",
    icon: "📋",
    desc: "Numbered methodology steps",
    dur: 240,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "steps", l: "Steps", t: "paste-lines", d: ["Step one", "Step two", "Step three"] },
      { k: "formula", l: "Formula / Key Insight", t: "text", d: "" },
      { k: "accentColor", l: "Accent", t: "color", d: "#00c358" },
    ],
  },
  {
    id: "Comparable",
    name: "T11: Comparable Card",
    icon: "🔄",
    desc: "'This is like that' comparison",
    dur: 180,
    fields: [
      { k: "subjectA.name", l: "Subject A", t: "text", d: "" },
      { k: "subjectA.detail", l: "A Detail", t: "text", d: "" },
      { k: "subjectA.stat", l: "A Stat", t: "text", d: "" },
      { k: "subjectB.name", l: "Subject B", t: "text", d: "" },
      { k: "subjectB.detail", l: "B Detail", t: "text", d: "" },
      { k: "subjectB.stat", l: "B Stat", t: "text", d: "" },
      { k: "connector", l: "Connector", t: "text", d: "IS COMPARABLE TO" },
      { k: "negated", l: "Negated (NOT)", t: "toggle", d: false },
    ],
  },
  {
    id: "LowerThird",
    name: "T12: Lower Third",
    icon: "🏷️",
    desc: "Classic broadcast lower third — speaker or source credit",
    dur: 150,
    fields: [
      { k: "primary", l: "Primary", t: "text", d: "" },
      { k: "secondary", l: "Secondary", t: "text", d: "" },
      { k: "accentColor", l: "Accent", t: "color", d: "#00c358" },
      { k: "position", l: "Position", t: "select", o: ["left", "right"], d: "left" },
    ],
  },
  {
    id: "HeatMap",
    name: "T13: Heat Map",
    icon: "🟥",
    desc: "Grid of cells with color intensity — show patterns across two axes",
    dur: 210,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "xLabels", l: "Column Labels", t: "text-list", ph: "1-3,4-6,7-9,10+", d: ["1-3", "4-6", "7-9", "10+"] },
      { k: "yLabels", l: "Row Labels", t: "text-list", ph: "1st,2nd,3rd,4th", d: ["1st", "2nd", "3rd", "4th"] },
      { k: "data", l: "Data (rows of numbers)", t: "textarea", d: [[75,68,52,41],[71,60,48,33],[80,65,55,38],[78,62,50,35]] },
      { k: "colorLow", l: "Low Color", t: "color", d: "#1E1E32" },
      { k: "colorHigh", l: "High Color", t: "color", d: "#00c358" },
      { k: "showValues", l: "Show Values", t: "toggle", d: true },
    ],
  },
  {
    id: "ScatterPlot",
    name: "T14: Scatter Plot",
    icon: "📊",
    desc: "X/Y scatter plot — find outliers and clusters",
    dur: 240,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "xLabel", l: "X-Axis Label", t: "text", d: "" },
      { k: "yLabel", l: "Y-Axis Label", t: "text", d: "" },
      { k: "points", l: "Points (label, x, y)", t: "textarea", d: [{ label: "KC", x: 420, y: 4.9 }] },
      { k: "quadrants", l: "Quadrant Labels", t: "textarea", d: {} },
    ],
  },
  {
    id: "FlexTable",
    name: "T15: Flex Table",
    icon: "📋",
    desc: "Flexible table — variable columns, variable rows",
    dur: 210,
    fields: [
      { k: "title", l: "Title", t: "text", d: "" },
      { k: "columns", l: "Columns (header + align)", t: "textarea", d: [{ header: "Player", align: "left" }, { header: "YDS", align: "right" }] },
      { k: "rows", l: "Rows", t: "paste-table", d: [{ cells: ["Mahomes", "312"], highlight: true }] },
      { k: "highlightColor", l: "Highlight Color", t: "color", d: "#00c358" },
      { k: "showRank", l: "Show Rank", t: "toggle", d: false },
    ],
  },
];
